# basic
title: cry101
subtitle: You Are The JavaScript In My HTML
favicon: favicon.ico

avatar: images/avatar.png
banner_small: images/banner-small.png
banner_large: images/banner-large.png

# disqus
# disqus_shortname: drakeleung
duoshuo_shortname: cry101

# social
social:
  github: https://github.com/cry101
  weibo: http://weibo.com/2070791647/profile?topnav=1&wvr=6
  #Others: https://www.zhihu.com/people/chen-ruo-yao-42

# nav #
nav:
  home: .
  archive: archives
  about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false


google_anlytics: # Put tracking ID here

# rss
rss: /atom.xml

#打赏
donate:
  enable: true
  wechat: images/wechatImage.jpg
  alipay: images/alipayImage.jpg

